source 'https://rubygems.org'

gem 'jquery-rails'
gem 'kaminari'
gem 'mysql2'
gem 'rails',          '3.2.1'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier',     '>= 1.0.3'
end

group :development, :test do
  gem "lava", :path => "../../"
  gem 'ruby-debug19',   :require => 'ruby-debug'
  gem 'thin'
end

group :production do
  # gem "lava", :git => "git://github.com/wilde4/lava_gem.git"
end

group :test do
  gem "lava", :path => "../../"
  gem "cucumber-rails", :require => false
  gem "database_cleaner"
  gem "factory_girl"
  gem "launchy"
  gem "pickle"
  gem "rspec-rails"
  gem "shoulda"
  gem "watchr"
end